name: DS Final Continuous Runner

on:
  workflow_dispatch:  # Run manually
  schedule:
    - cron: '30 3 * * 1-5'  # optional: runs automatically at 9:00 AM IST (3:30 UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 1200  # = 20 hours
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run DS Final Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLIENT_CODE: ${{ secrets.CLIENT_CODE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOTP: ${{ secrets.TOTP }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python dsfinal.py
