name: Ultimate Master Algo Bot

on:
  schedule:
    # Run Monday to Friday at 9:10 AM IST (3:40 UTC)
    - cron: '40 3 * * 1-5'
  workflow_dispatch:  # Manual trigger

jobs:
  run-algo:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # Max 8 hours

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: Run Algo Bot
      run: |
        python main.py  # Replace with your script entry point
