name: Ultimate Master Algo Bot

on:
  schedule:
    # Run Monday to Friday at 9:10 AM IST (3:40 UTC)
    - cron: '40 3 * * 1-5'
  workflow_dispatch:

jobs:
  run-algo:
    runs-on: ubuntu-latest
    timeout-minutes: 480

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Upgrade pip, setuptools, wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: Run bot
      run: |
        python main.py
